apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: "{{ .Values.name }}-hpa"
    labels:
        app: {{ .Values.name }}
    namespace: {{ .Values.environment }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: "{{ .Values.name }}-deployment"
    {{- if .Values.highAvailability }}
    minReplicas: 2
    {{- else }}
    minReplicas: 1
    {{- end }}
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
