apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.name }}-secret"
    namespace: {{ .Values.environment }}
type: Opaque
stringData:
    {{- range $key, $value := .Values.environmentVariables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.name }}-image-secret"
    label:
        app: {{ .Values.name }}
        namespace: {{ .Values.environment }}
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: >
        {{- $server := .Values.image.registry -}}
        {{- $auth := printf "%s:%s" .Values.image.username .Values.image.password | b64enc -}}
        {{- dict "auths" (dict $server (dict "username" .Values.image.username "password" .Values.image.password "auth" $auth)) | toJson -}}

    