apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.name }}-secret"
    namespace: {{ .Values.environment }}
    labels:
        app: {{ .Values.name }}
type: Opaque
stringData:
    {{- range $key, $value := .Values.environmentVariables }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.name }}-image-secret"
    namespace: {{ .Values.environment }}
    labels:
        app: {{ .Values.name }}
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: {{ dict "auths" (dict (.Values.image.registry | trimSuffix "/") (dict "username" .Values.image.username "password" .Values.image.password "auth" (printf "%s:%s" .Values.image.username .Values.image.password | b64enc))) | toJson | quote }}

    